export const galleryItems = [
  {
    small: "./assets/arch-1-small.jpg",
    jpg: "./assets/arch-1.jpg",
    jpgFull: "./assets/arch-1x2.jpg",
    webp: "./assets/arch-1.webp",
    webpFull: "./assets/arch-1x2.webp",
    description: "Cozy apartment in a quiet neighborhood.",
  },
  {
    small: "./assets/arch-2-small.jpg",
    jpg: "./assets/arch-2.jpg",
    jpgFull: "./assets/arch-2x2.jpg",
    webp: "./assets/arch-2.webp",
    webpFull: "./assets/arch-2x2.webp",
    description: "Modern apartment with luxurious amenities.",
  },
  {
    small: "./assets/house-1-small.jpg",
    jpg: "./assets/house-1.jpg",
    jpgFull: "./assets/house-1x2.jpg",
    webp: "./assets/house-1.webp",
    webpFull: "./assets/house-1x2.webp",
    description: "Charming apartment with vintage vibes.",
  },
  {
    small: "./assets/house-2-small.jpg",
    jpg: "./assets/house-2.jpg",
    jpgFull: "./assets/house-2x2.jpg",
    webp: "./assets/house-2.webp",
    webpFull: "./assets/house-2x2.webp",
    description: "Bright and airy apartment with a balcony.",
  },
  {
    small: "./assets/house-3-small.jpg",
    jpg: "./assets/house-3.jpg",
    jpgFull: "./assets/house-3x2.jpg",
    webp: "./assets/house-3.webp",
    webpFull: "./assets/house-3x2.webp",
    description:
      "Spacious loft-style apartment with industrial design elements.",
  },
  {
    small: "./assets/int-4-small.jpg",
    jpg: "./assets/int-4.jpg",
    jpgFull: "./assets/int-4x2.jpg",
    webp: "./assets/int-4.webp",
    webpFull: "./assets/int-4x2.webp",
    description: "Charming apartment with a private garden.",
  },
  {
    small: "./assets/int-2-small.jpg",
    jpg: "./assets/int-2.jpg",
    jpgFull: "./assets/int-2x2.jpg",
    webp: "./assets/int-2.webp",
    webpFull: "./assets/int-2x2.webp",
    description: "Cosy apartment in a charming historic building.",
  },
  {
    small: "./assets/int-3-small.jpg",
    jpg: "./assets/int-3.jpg",
    jpgFull: "./assets/int-3x2.jpg",
    webp: "./assets/int-3.webp",
    webpFull: "./assets/int-3x2.webp",
    description: "Contemporary apartment with panoramic views of the city.",
  },
  {
    small: "./assets/kitchen-1-small.jpg",
    jpg: "./assets/kitchen-1.jpg",
    jpgFull: "./assets/kitchen-1x2.jpg",
    webp: "./assets/kitchen-1.webp",
    webpFull: "./assets/kitchen-1x2.webp",
    description: "Sleek and minimalistic apartment in a high-rise building.",
  },
  {
    small: "./assets/kitchen-2-small.jpg",
    jpg: "./assets/kitchen-2.jpg",
    jpgFull: "./assets/kitchen-2x2.jpg",
    webp: "./assets/kitchen-2.webp",
    webpFull: "./assets/kitchen-2x2.webp",
    description: "Elegant apartment with luxurious finishes and amenities.",
  },
  {
    small: "./assets/kitchen-3-small.jpg",
    jpg: "./assets/kitchen-3.jpg",
    jpgFull: "./assets/kitchen-3x2.jpg",
    webp: "./assets/kitchen-3.webp",
    webpFull: "./assets/kitchen-3x2.webp",
    description: "Quaint apartment in a picturesque neighborhood.",
  },
  {
    small: "./assets/kitchen-4-small.jpg",
    jpg: "./assets/kitchen-4.jpg",
    jpgFull: "./assets/kitchen-4x2.jpg",
    webp: "./assets/kitchen-4.webp",
    webpFull: "./assets/kitchen-4x2.webp",
    description: "Modern penthouse with stunning views of the skyline.",
  },
];